### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ghost** [alanmarazzi/mepcheck#2] opened 2018-04-10 11:31 UTC
I'm getting the following error, while trying to run the program:

```
jens@debian-vm:~/mepcheck$ python3.5 mepcheckCLI.py -c denmark
Traceback (most recent call last):
  File "mepcheckCLI.py", line 2, in <module>
    mepcheck_cli.cli()
  File "/home/jens/mepcheck/mepcheck/mepcheck_cli.py", line 16, in cli
    get_meps(args.country)
  File "/home/jens/mepcheck/mepcheck/mepcheck.py", line 36, in get_meps
    print(t)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 284: ordinal not in range(128)
```

I don't know Python very well, so I'm not sure what's wrong.

**Comment by alanmarazzi** [comment] 2018-04-11 12:53
I just tried to reproduce it and I didn't have any issues:

![screenshot_1](https://user-images.githubusercontent.com/14168642/38617539-995964da-3d97-11e8-98b7-280f0e54c6b4.png)

I guess you have issues with characters in names such as: ` Jørn Dohrmann`. You should verify your terminal supports UTF-8 encoding, and I'm guessing that might be the issue considering that Python is failing at `print(t)` while everything works smoothly up to that point.

Let me know if that was the issue or if you experiment some other problem, thanks

**Comment by alanmarazzi** [comment] 2018-04-18 15:51
Closing since there was no answer and it likely was an out of scope issue

**Closed as completed by alanmarazzi** 2018-04-18 15:51 UTC
